### ISSUE TITLE
Bug: Unable to run due to missing libstdc++.so.6

### ISSUE THREAD

**Issue by Ash3781** [TagStudioDev/TagStudio#209]
Hey, I just tried to run the `TagStudio.sh` script, however it gave me the following error:
```
Traceback (most recent call last):
  File "/home/ash/git/TagStudio/tagstudio/tag_studio.py", line 7, in <module>
    from src.core.ts_core import TagStudioCore
  File "/home/ash/git/TagStudio/tagstudio/src/core/ts_core.py", line 10, in <module>
    from src.core.library import Entry, Library
  File "/home/ash/git/TagStudio/tagstudio/src/core/library.py", line 22, in <module>
    import ujson
ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory
```
I am using an AMD64 architecture and running NixOS on my machine, hence why I am unable to use the packages from the release files, NixOS is unable to run dynamically linked executables, if anyone needs more info please let me know

**Comment by xarvex** [comment]
This should be fixed thanks to #244 being merged in, please reopen if this persists.

**Comment by Ash3781** [comment]
I am unable to reopen the issue, but the issue is not resolved, apart from the line numbers I'm still getting the very same error
![image](https://github.com/TagStudioDev/TagStudio/assets/37660156/160cc0a4-67a7-4b4d-9947-1bdb48d6fe37)

**Comment by xarvex** [comment]
Is this after using the provided dev shell in the flake? (`nix develop`)

**Comment by Ash3781** [comment]
I have no idea how flakes work, I am trying to run the `TagStudio.sh` script

**Comment by Ash3781** [comment]
Okay, so when running `nix develop` in the git repository and then executing `./TagStudio.sh` works and I get the TagStudio GUI, is there a way to integrate it "like a normal program" without needing to enter the two commands?

**Comment by xarvex** [comment]
NixOS support is very experimental and it only just got to a state of working at all. I am investing time in exploring how it can be built standalone once #229 is merged.
On that note, you may get an error `path/to/TagStudio/.venv/bin/pip: cannot execute: required file not found`, this is due to the virtual environment looking for the previous store pip. Until #229 gets merged which should fix this, a `rm -rf .venv` will do the trick.
